### ISSUE TITLE
IRI is not compacted when using a certain context format

### ISSUE THREAD

**Issue by RobinDeBaets** [rubensworks/jsonld-context-parser.js#22]
I'm trying to compact the path `npmd:@comunica/actor-init-hello-world/ActorInitHelloWorld` using `compactIri`
When using the following context, the path doesn't get compacted at all: 
```
{
  "@context": [
    "https://linkedsoftwaredependencies.org/bundles/npm/componentsjs/^3.0.0/components/context.jsonld",
    {
      "npmd": "https://linkedsoftwaredependencies.org/bundles/npm/",
      "chw": "npmd:@comunica/actor-init-hello-world/",
      "files-chw": "chw:^1.0.0/",
      "config-example": "files-chw:config/config-example.json#",

      "ActorInitHelloWorld": "chw:Actor/Init/HelloWorld",
      "hello": "chw:hello"
    }
  ]
}
```
When using the following context, the path gets compacted to `chw:ActorInitHelloWorld`, which is still not ideal (see #21):
```
{
      "npmd": "https://linkedsoftwaredependencies.org/bundles/npm/",
      "chw": "npmd:@comunica/actor-init-hello-world/",
      "files-chw": "chw:^1.0.0/",
      "config-example": "files-chw:config/config-example.json#",

      "ActorInitHelloWorld": "chw:Actor/Init/HelloWorld",
      "hello": "chw:hello"
    }
```

**Comment by rubensworks** [comment]
It looks like this was not a bug after all.
Compaction and expansion can only be done on contexts that have been run through the context parser.

When using TS, your compiler will help you with that.
I've now added some runtime checks for JS users as well.
