### ISSUE TITLE
Can't parse IIIF Presentation v3 context

### ISSUE THREAD

**Issue by sandhose** [rubensworks/jsonld-context-parser.js#35]
I've been trying to use `jsonld-streaming-parser` to parse [IIIF Presentation manifests](https://iiif.io/api/presentation/3.0/#52-manifest), but it fails when parsing the IIIF presentation context: http://iiif.io/api/presentation/3/context.json

It fails with this message: `ErrorCoded: Cannot use 'in' operator to search for '@base' in http://iiif.io/api/image/1/context.json`, which seems to come from here: https://github.com/rubensworks/jsonld-context-parser.js/blob/461c626e19f2bb3afdb50c12f1bb4b2501d608b8/lib/ContextParser.ts#L550

At this point, `options.parentContext` is a string, so `'@base' in options.parentContext` fails.

The example IIIF manifest seems to [work find in the playground](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Fiiif.io%2Fapi%2Fpresentation%2F3%2Fcontext.json%22%2C%22id%22%3A%22https%3A%2F%2Fexample.org%2Fiiif%2Fbook1%2Fmanifest%22%2C%22type%22%3A%22Manifest%22%2C%22label%22%3A%7B%22en%22%3A%5B%22Book%201%22%5D%7D%2C%22metadata%22%3A%5B%7B%22label%22%3A%7B%22en%22%3A%5B%22Author%22%5D%7D%2C%22value%22%3A%7B%22none%22%3A%5B%22Anne%20Author%22%5D%7D%7D%2C%7B%22label%22%3A%7B%22en%22%3A%5B%22Published%22%5D%7D%2C%22value%22%3A%7B%22en%22%3A%5B%22Paris%2C%20circa%201400%22%5D%2C%22fr%22%3A%5B%22Paris%2C%20environ%201400%22%5D%7D%7D%2C%7B%22label%22%3A%7B%22en%22%3A%5B%22Notes%22%5D%7D%2C%22value%22%3A%7B%22en%22%3A%5B%22Text%20of%20note%201%22%2C%22Text%20of%20note%202%22%5D%7D%7D%2C%7B%22label%22%3A%7B%22en%22%3A%5B%22Source%22%5D%7D%2C%22value%22%3A%7B%22none%22%3A%5B%22%3Cspan%3EFrom%3A%20%3Ca%20href%3D%5C%22https%3A%2F%2Fexample.org%2Fdb%2F1.html%5C%22%3ESome%20Collection%3C%2Fa%3E%3C%2Fspan%3E%22%5D%7D%7D%5D%2C%22summary%22%3A%7B%22en%22%3A%5B%22Book%201%2C%20written%20by%20Anne%20Author%2C%20published%20in%20Paris%20around%201400.%22%5D%7D%2C%22thumbnail%22%3A%5B%7B%22id%22%3A%22https%3A%2F%2Fexample.org%2Fiiif%2Fbook1%2Fpage1%2Ffull%2F80%2C100%2F0%2Fdefault.jpg%22%2C%22type%22%3A%22Image%22%2C%22format%22%3A%22image%2Fjpeg%22%2C%22service%22%3A%5B%7B%22id%22%3A%22https%3A%2F%2Fexample.org%2Fiiif%2Fbook1%2Fpage1%22%2C%22type%22%3A%22ImageService3%22%2C%22profile%22%3A%22level1%22%7D%5D%7D%5D%2C%22viewingDirection%22%3A%22right-to-left%22%2C%22behavior%22%3A%5B%22paged%22%5D%2C%22navDate%22%3A%221856-01-01T00%3A00%3A00Z%22%2C%22rights%22%3A%22http%3A%2F%2Fcreativecommons.org%2Flicenses%2Fby%2F4.0%2F%22%2C%22requiredStatement%22%3A%7B%22label%22%3A%7B%22en%22%3A%5B%22Attribution%22%5D%7D%2C%22value%22%3A%7B%22en%22%3A%5B%22Provided%20by%20Example%20Organization%22%5D%7D%7D%2C%22provider%22%3A%5B%7B%22id%22%3A%22https%3A%2F%2Fexample.org%2Fabout%22%2C%22type%22%3A%22Agent%22%2C%22label%22%3A%7B%22en%22%3A%5B%22Example%20Organization%22%5D%7D%2C%22homepage%22%3A%5B%7B%22id%22%3A%22https%3A%2F%2Fexample.org%2F%22%2C%22type%22%3A%22Text%22%2C%22label%22%3A%7B%22en%22%3A%5B%22Example%20Organization%20Homepage%22%5D%7D%2C%22format%22%3A%22text%2Fhtml%22%7D%5D%2C%22logo%22%3A%5B%7B%22id%22%3A%22https%3A%2F%2Fexample.org%2Fservice%2Finst1%2Ffull%2Fmax%2F0%2Fdefault.png%22%2C%22type%22%3A%22Image%22%2C%22format%22%3A%22image%2Fpng%22%2C%22service%22%3A%5B%7B%22id%22%3A%22https%3A%2F%2Fexample.org%2Fservice%2Finst1%22%2C%22type%22%3A%22ImageService3%22%2C%22profile%22%3A%22level2%22%7D%5D%7D%5D%2C%22seeAlso%22%3A%5B%7B%22id%22%3A%22https%3A%2F%2Fdata.example.org%2Fabout%2Fus.jsonld%22%2C%22type%22%3A%22Dataset%22%2C%22format%22%3A%22application%2Fld%2Bjson%22%2C%22profile%22%3A%22https%3A%2F%2Fschema.org%2F%22%7D%5D%7D%5D%2C%22homepage%22%3A%5B%7B%22id%22%3A%22https%3A%2F%2Fexample.org%2Finfo%2Fbook1%2F%22%2C%22type%22%3A%22Text%22%2C%22label%22%3A%7B%22en%22%3A%5B%22Home%20page%20for%20Book%201%22%5D%7D%2C%22format%22%3A%22text%2Fhtml%22%7D%5D%2C%22service%22%3A%5B%7B%22id%22%3A%22https%3A%2F%2Fexample.org%2Fservice%2Fexample%22%2C%22type%22%3A%22ExampleExtensionService%22%2C%22profile%22%3A%22https%3A%2F%2Fexample.org%2Fdocs%2Fexample-service.html%22%7D%5D%2C%22seeAlso%22%3A%5B%7B%22id%22%3A%22https%3A%2F%2Fexample.org%2Flibrary%2Fcatalog%2Fbook1.xml%22%2C%22type%22%3A%22Dataset%22%2C%22format%22%3A%22text%2Fxml%22%2C%22profile%22%3A%22https%3A%2F%2Fexample.org%2Fprofiles%2Fbibliographic%22%7D%5D%2C%22rendering%22%3A%5B%7B%22id%22%3A%22https%3A%2F%2Fexample.org%2Fiiif%2Fbook1.pdf%22%2C%22type%22%3A%22Text%22%2C%22label%22%3A%7B%22en%22%3A%5B%22Download%20as%20PDF%22%5D%7D%2C%22format%22%3A%22application%2Fpdf%22%7D%5D%2C%22partOf%22%3A%5B%7B%22id%22%3A%22https%3A%2F%2Fexample.org%2Fcollections%2Fbooks%2F%22%2C%22type%22%3A%22Collection%22%7D%5D%2C%22start%22%3A%7B%22id%22%3A%22https%3A%2F%2Fexample.org%2Fiiif%2Fbook1%2Fcanvas%2Fp2%22%2C%22type%22%3A%22Canvas%22%7D%2C%22services%22%3A%5B%7B%22%40id%22%3A%22https%3A%2F%2Fexample.org%2Fiiif%2Fauth%2Flogin%22%2C%22%40type%22%3A%22AuthCookieService1%22%2C%22profile%22%3A%22http%3A%2F%2Fiiif.io%2Fapi%2Fauth%2F1%2Flogin%22%2C%22label%22%3A%22Login%20to%20Example%20Institution%22%2C%22service%22%3A%5B%7B%22%40id%22%3A%22https%3A%2F%2Fexample.org%2Fiiif%2Fauth%2Ftoken%22%2C%22%40type%22%3A%22AuthTokenService1%22%2C%22profile%22%3A%22http%3A%2F%2Fiiif.io%2Fapi%2Fauth%2F1%2Ftoken%22%7D%5D%7D%5D%2C%22items%22%3A%5B%7B%22id%22%3A%22https%3A%2F%2Fexample.org%2Fiiif%2Fbook1%2Fcanvas%2Fp1%22%2C%22type%22%3A%22Canvas%22%2C%22label%22%3A%7B%22none%22%3A%5B%22p.%201%22%5D%7D%7D%5D%2C%22structures%22%3A%5B%7B%22id%22%3A%22https%3A%2F%2Fexample.org%2Fiiif%2Fbook1%2Frange%2Ftop%22%2C%22type%22%3A%22Range%22%7D%5D%2C%22annotations%22%3A%5B%7B%22id%22%3A%22https%3A%2F%2Fexample.org%2Fiiif%2Fbook1%2Fannotations%2Fp1%22%2C%22type%22%3A%22AnnotationPage%22%2C%22items%22%3A%5B%5D%7D%5D%7D), so I'm assuming the document and the context are valid.

Can be reproduced with the CLI:

```
$ jsonld-context-parse url http://iiif.io/api/presentation/3/context.json
Cannot use 'in' operator to search for '@base' in http://iiif.io/api/image/1/context.json
```

**Comment by rubensworks** [comment]
Thanks for reporting! Fixed in 2.1.2.
