### ISSUE TITLE
Faulty validation of @container in JSON-LD version 1.1

### ISSUE THREAD

**Issue by gebsl** [rubensworks/jsonld-context-parser.js#40]
Following setup:

I have a JSON-LD document with an @import statement (shortened):

```jsonld
{
  "@context": {
    "@version": 1.1,    
    "@import": "http://localhost:8080/some-document.jsonld",
  },
  "@graph": [
  ]
}
```

The referenced @import resolves to this document (shortened):

```jsonld
{
  "@context": {
    "rdfs": "https://www.w3.org/2000/01/rdf-schema#",
    "xsd": "https://www.w3.org/2001/XMLSchema#",
    "owl": "https://www.w3.org/2002/07/owl#",
    "subClassOf": {
      "@id": "rdfs:subClassOf",
      "@type": "@id"
    },
    "import": {
      "@id": "owl:import",
      "@type": "@id"
    },
    "entry": {
      "@id": "some:entry",
      "@container": "@language"
    }
  }
}
```

Parsing the document gives the follwing error:
`Error: Invalid term @container for 'label' ('0'), must be one of @list, @set, @index, @language, @graph, @id, @type`

Parsing is done via `jsonld-streaming-parser`.

The error is thrown on this line:
https://github.com/rubensworks/jsonld-context-parser.js/blob/c1abad92757586d1749e89959abec3a8cd9d54aa/lib/ContextParser.ts#L492

Actually, @language should be a valid term, as it is also used in the specification:
https://www.w3.org/TR/json-ld11/#example-71-language-map-expressing-a-property-in-three-languages

Also, json-ld playground says this is valid JSON-LD
https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22rdfs%22%3A%22https%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%22%2C%22xsd%22%3A%22https%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%22%2C%22owl%22%3A%22https%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%22%2C%22subClassOf%22%3A%7B%22%40id%22%3A%22rdfs%3AsubClassOf%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22import%22%3A%7B%22%40id%22%3A%22owl%3Aimport%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22entry%22%3A%7B%22%40id%22%3A%22some%3Aentry%22%2C%22%40container%22%3A%22%40language%22%7D%7D%7D&context=%7B%7D

What I don't understand: Why is there a loop over the keys of `objectValue` in your code? As I understand, `objectValue` should already be a string and looping over it does not make sense to me.

Thanks in advance for your help, best regards,
gebsl

**Comment by rubensworks** [comment]
For performance reasons, this lib internally converts container entries to hashes here: https://github.com/rubensworks/jsonld-context-parser.js/blob/c1abad92757586d1749e89959abec3a8cd9d54aa/lib/ContextParser.ts#L220-L224

I suspect for some reason this code is not being called for imported contexts, which seems to be the root cause of this issue.

**Comment by gebsl** [comment]
Hi @rubensworks,

I've looked into the issue and a proposed solution.

When loading context from an `@import` keyword, the newly loaded context is not parsed, but passed "as is" to the initial context object. See:
https://github.com/rubensworks/jsonld-context-parser.js/blob/c1abad92757586d1749e89959abec3a8cd9d54aa/lib/ContextParser.ts#L869

Proposed solution:
Let the newly loaded context also go through the parse function, so everything that is done on the original context is also done on the newly imported context.

I will submit a PR that contains the proposed fix.
