### ISSUE TITLE
does the commandline tool work?

### ISSUE THREAD

**Issue by sanuann** [rubensworks/jsonld-context-parser.js#7]
I've tried using the command line tool usage (eg. jsonld-context-parse url http://json-ld.org/contexts/person.jsonld) and get an error saying: 
"jsonld-context-parse: command not found".

I also did the npm install step before doing the above.

**Comment by rubensworks** [comment]
What version are you using?

This should have been fixed in release 1.0.1 thanks to c0e268890c19e0b28629ac4ea1e92e4a258b8049.

**Comment by sanuann** [comment]
jsonld-context-parser@1.0.1

Can you check if it works for you?

**Comment by rubensworks** [comment]
Works fine for me:

```
rtaelman@ea06c070 ~ 🔷  jsonld-context-parse url http://json-ld.org/contexts/person.jsonld
{
  "Person": "http://xmlns.com/foaf/0.1/Person",
  "xsd": "http://www.w3.org/2001/XMLSchema#",
  "name": "http://xmlns.com/foaf/0.1/name",
  "nickname": "http://xmlns.com/foaf/0.1/nick",
...
```

Are you sure you did a global install (`npm install -g jsonld-context-parser`)? Because npm will not expose the script for a local install.

**Comment by sanuann** [comment]
<img width="1206" alt="screen shot 2018-12-11 at 10 09 40 am" src="https://user-images.githubusercontent.com/5114945/49809564-3cc99680-fd2d-11e8-9ef0-d56cbf4f6542.png">

**Comment by rubensworks** [comment]
That's a different error at least.

But it looks like you're getting some errors during your installation. The last error is related to `node-fetch`, which is probably due to a corrupted installation. I suggest that you look into those first errors, this does not seem related to jsonld-context-parser.
